sudo: required

language: csharp
mono: none
dotnet: 2.1

branches:
  only:
  - master

services:
  - docker

script:
  - dotnet build
# Soon we'll setup tests. For now just implement building and publish to docker.

deploy: # This won't run if dotnet build fails.
  - dotnet restore # Restore the packages.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t binzy/haruna .
  - docker push binzy/haruna